### ISSUE TITLE
using a non-integer number instead of an integer will result in an error in the future

### ISSUE THREAD

**Issue by jmao2014** [zmzhang/libPeak#1]
peak_detection.py
line 136: "ridge.shape[1] / 2" is not necessary an integer.

**Comment by zmzhang** [comment]
Thanks for your feedback!
This issue was fixed by converting float to int for indexing ridge.
Please see [this commit](https://github.com/zmzhang/libPeak/commit/17908f755adfcbd944fb86d8cc8c818aeba80dfe) for details.
