### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by johndoe210** [zmzhang/libPeak#2]
Hi, thanks for the great peak detection algorithm and paper.

Would you consider adding a license to this repository so that your code could be used by others? If you prefer to keep it all rights reserved so that no one can copy/use the code (as it is now without any license file), that's completely fine, it would just be nice to explicitly state so.

Thanks.

**Comment by zmzhang** [comment]
Already create the License file.
Please see the following URL:
https://github.com/zmzhang/libPeak/blob/master/LICENSE
